### ISSUE TITLE
Use rustfmt for code formatting

### ISSUE THREAD

**Issue by TheDan64** [TheDan64/inkwell#75]
**Is your feature request related to a problem? Please describe.**
@longwusha had a great suggestion - we should have code styling preferences. Particularly via rustfmt.

**Describe the solution you'd like**
We should use rustfmt to standardize code style.

**Describe possible drawbacks to your solution**
My ideal configuration for rustfmt uses unstable options, but this project is on stable. So I do not wish to enforce nightly rustfmt.

**Additional context**
Stabilization checklist **WIP**:
- [ ] comment_width = 100 - https://github.com/rust-lang/rustfmt/issues/3349
- [ ] format_doc_comments = true  - https://github.com/rust-lang/rustfmt/issues/3348
- [ ] match_arm_blocks = false - https://github.com/rust-lang/rustfmt/issues/3373
- [x] match_block_trailing_comma = true - https://github.com/rust-lang/rustfmt/issues/3380
- [x] max_width = 120
- [x] merge_derives = true
- [x] merge_imports = true - https://github.com/rust-lang/rustfmt/issues/3362
- [x] newline_style = "Unix"
- [x] use_field_init_shorthand = true
- [x] use_try_shorthand = true
- [ ] wrap_comments = true - https://github.com/rust-lang/rustfmt/issues/3347

**Comment by TheDan64** [comment]
Blocked until rustfmt v2 which will let you use unstable features on stable

**Comment by TheDan64** [comment]
Going to add the rustfmt settings that are available now & we can add more later
